import type { Metadata } from "next";
import "./globals.css";
import "ress";
import Layout from "./_components/Layout";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Providers } from "./_components/Providers";

export const metadata: Metadata = {
  title: "オモコロアーカイブ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <NuqsAdapter>
          <Providers>
            <Layout>{children}</Layout>
          </Providers>
        </NuqsAdapter>
      </body>
    </html>
  );
}
